package com.liferay.ide.projects.todo.model.impl;

import com.liferay.ide.projects.todo.model.Todo;
import com.liferay.ide.projects.todo.service.TodoLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Todo service. Represents a row in the &quot;Todos_Todo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TodoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TodoImpl
 * @see com.liferay.ide.projects.todo.model.Todo
 * @generated
 */
public abstract class TodoBaseImpl extends TodoModelImpl implements Todo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a todo model instance should use the {@link Todo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TodoLocalServiceUtil.addTodo(this);
        } else {
            TodoLocalServiceUtil.updateTodo(this);
        }
    }
}
